config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

  get 'home/about'
  get 'home/characters'
  get 'home/characters/:id', to: 'home#show', as: 'home_character'
  get 'home/clans'
  get 'clans/:id/characters', to: 'home#clan_characters', as: 'clan_characters'
  get 'home/search_characters', to: 'home#search_characters', as: 'search_characters'
  get "up" => "rails/health#show", as: :rails_health_check



end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

         def self.ransackable_attributes(auth_object = nil)
          ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
        end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true
  validates :id, uniqueness: true
  validates :name, confirmation: { case_sensitive: false }

  # Associations
  # Jutsus
  has_many :jutsus, dependent: :destroy
  # Clans
  has_many :character_clans, dependent: :destroy
  has_many :clans, through: :character_clans

  def self.ransackable_associations(auth_object = nil)
    ["character_clans", "clans", "jutsus"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["birthdate", "created_at", "id", "id_value", "image_1", "image_2", "name", "updated_at"]
  end



end

app/models/character_clan.rb
class CharacterClan < ApplicationRecord
  validates :character_id, presence: true
  validates :clan_id, presence: true
  belongs_to :character
  belongs_to :clan

  def self.ransackable_attributes(auth_object = nil)
    ["character_id", "clan_id", "created_at", "id", "id_value", "updated_at"]
  end
end

app/models/clan.rb
class Clan < ApplicationRecord
  validates :name, presence: true
  validates :name, confirmation: { case_sensitive: false }
  # Associations
  has_many :character_clans, dependent: :destroy
  has_many :characters, through: :character_clans

  def self.ransackable_associations(auth_object = nil)
    ["character_clans", "characters"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "name", "updated_at"]
  end
end

app/models/jutsu.rb
class Jutsu < ApplicationRecord
  validates :name, presence: true
  validates :character_id, presence: true
  belongs_to :character

  def self.ransackable_attributes(auth_object = nil)
    ["character_id", "created_at", "id", "id_value", "name", "updated_at"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @characters = Character.paginate(page: params[:page], per_page: 10)
    @clans = Clan.all
  end

  def about
  end

  def characters
    @characters = Character.paginate(page: params[:page], per_page: 10)
  end

  def show
    @character = Character.find(params[:id])
    @jutsus = @character.jutsus.paginate(page: params[:page], per_page: 10)
    @clan_name = @character.clans.first.name if @character.clans.any?
  end

  def search_characters
    @characters = filtered_characters.paginate(page: params[:page], per_page: 10)

    render 'search'
  end

  def clans
    @clans = Clan.all
  end

  def clan_characters
    @clan = Clan.find(params[:id])
    @characters = @clan.characters.paginate(page: params[:page], per_page: 10)
  end

  private

  def filtered_characters
    characters = Character.joins(:character_clans).where.not(character_clans: { clan_id: nil })

    characters = characters.where('name LIKE ?', "%#{params[:query]}%") if params[:query].present?
    characters = characters.where(character_clans: { clan_id: params[:clan_id] }) if params[:clan_id].present? && params[:clan_id].to_i > 0

    characters.distinct
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
    </div>
</div>

        <footer class="bg-white dark:bg-gray-900 px-6">
        <span class="text-gray-700 transition-colors duration-300 dark:text-gray-300 hover:text-blue-500 dark:hover:text-blue-400">
            Created by Daniel
        </span>
        </footer>

app/views/home/_header.html.erb
<!-- component -->
<script src="//unpkg.com/alpinejs" defer></script>

<div class="w-full min-h-screen bg-white dark:bg-gray-900">
    <div class="container relative flex flex-col min-h-screen px-6 py-8 mx-auto">
        <nav class="md:flex md:items-center md:justify-between">
            <div class="flex items-center justify-between">
                <button class="md:hidden">
                    <span>
                        <svg class="w-6 h-6 fill-gray-800 dark:fill-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512">
                            <path
                                d="M310.6 361.4c12.5 12.5 12.5 32.75 0 45.25C304.4 412.9 296.2 416 288 416s-16.38-3.125-22.62-9.375L160 301.3L54.63 406.6C48.38 412.9 40.19 416 32 416S15.63 412.9 9.375 406.6c-12.5-12.5-12.5-32.75 0-45.25l105.4-105.4L9.375 150.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L160 210.8l105.4-105.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-105.4 105.4L310.6 361.4z" />
                        </svg>
                    </span>

                    <span>
                        <svg class="w-6 h-6 text-gray-800 dark:fill-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                            <path d="M0 96C0 78.33 14.33 64 32 64H416C433.7 64 448 78.33 448 96C448 113.7 433.7 128 416 128H32C14.33 128 0 113.7 0 96zM0 256C0 238.3 14.33 224 32 224H416C433.7 224 448 238.3 448 256C448 273.7 433.7 288 416 288H32C14.33 288 0 273.7 0 256zM416 448H32C14.33 448 0 433.7 0 416C0 398.3 14.33 384 32 384H416C433.7 384 448 398.3 448 416C448 433.7 433.7 448 416 448z" />
                        </svg>
                    </span>
                </button>

                <div class="flex items-center">
                <%= link_to root_path do %>
                    <%= image_tag 'logo.png', alt: 'Logo', class: 'h-20 w-20 mr-2 rounded-full border-2 border-white' %>
                <% end %>
                <%= link_to 'Naruto Rails Project', root_path, class: 'text-2xl font-bold text-gray-800 transition-colors duration-300 transform dark:text-white lg:text-3xl hover:text-gray-700 dark:hover:text-gray-300' %>
                </div>

            </div>

            <div class="absolute inset-x-0 z-20 w-full px-6 py-8 mt-8 space-y-6 transition-all duration-300 ease-in-out bg-white dark:bg-gray-900 top-16 md:bg-transparent md:dark:bg-transparent md:mt-0 md:p-0 md:top-0 md:relative md:w-auto md:opacity-100 md:translate-x-0 md:space-y-0 md:-mx-6 md:flex md:items-center">

                <%= link_to 'Home', root_path, class: 'block text-gray-600 transition-colors duration-300 dark:text-white md:px-6 hover:text-blue-500 dark:hover:text-blue-400'%>
                <%= link_to 'About', home_about_path, class: 'block text-gray-600 transition-colors duration-300 dark:text-white md:px-6 hover:text-blue-500 dark:hover:text-blue-400'%>
                <%= link_to 'Characters' , home_characters_path, class: 'block text-gray-600 transition-colors duration-300 dark:text-white md:px-6 hover:text-blue-500 dark:hover:text-blue-400'%>
                <%= link_to 'Clans', home_clans_path, class: 'block text-gray-600 transition-colors duration-300 dark:text-white md:px-6 hover:text-blue-500 dark:hover:text-blue-400' %>


            </div>
        </nav>

app/views/home/_pagination.html.erb
<div class="mt-6 flex justify-center space-x-2">
  <% if @characters.total_pages > 1 %>
    <% if @characters.current_page > 1 %>
      <%= link_to 'Previous', url_for(page: @characters.current_page - 1), class: 'px-3 py-2 bg-red-500 text-white rounded-lg hover:bg-blue-600' %>
    <% end %>
    
    <% first_page = @characters.current_page - 2 %>
    <% last_page = @characters.current_page + 2 %>
    
    <% if first_page > 1 %>
      <%= link_to 1, url_for(page: 1), class: 'px-3 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600' %>
      <% if first_page > 2 %>
        <span class="px-3 py-2">...</span>
      <% end %>
    <% end %>
    
    <% (first_page..last_page).each do |page| %>
      <% if page > 0 && page <= @characters.total_pages %>
        <%= link_to page, url_for(page: page), class: page == @characters.current_page ? 'px-3 py-2 bg-red-500 text-white rounded-lg hover:bg-blue-600' : 'px-3 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600' %>
      <% end %>
    <% end %>
    
    <% if last_page < @characters.total_pages %>
      <% if last_page < @characters.total_pages - 1 %>
        <span class="px-3 py-2">...</span>
      <% end %>
      <%= link_to @characters.total_pages, url_for(page: @characters.total_pages), class: 'px-3 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600' %>
    <% end %>
    
    <% if @characters.current_page < @characters.total_pages %>
      <%= link_to 'Next', url_for(page: @characters.current_page + 1), class: 'px-3 py-2 bg-red-500 text-white rounded-lg hover:bg-blue-600' %>
    <% end %>
  <% end %>
</div>

app/views/home/_searchForm.html.erb
<div class="mx-auto mb-6 text-center">
  <%= image_tag 'naruto_logo.png', alt: 'Logo', class: 'w-64 mr-2 inline-block ' %>
  <%= form_with url: search_characters_path, method: :get, local: true, class: "flex items-center space-x-2" do |form| %>
    <div class="mb-4">
      <%= form.text_field :query, class: "shadow appearance-none border rounded w-96 py-4 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Search characters by name..." %>
    </div>
    <div class="mb-4">
      <%= form.collection_select :clan_id, Clan.all, :id, :name, { include_blank: 'All Clans' }, class: "shadow appearance-none border rounded w-96 py-4 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
    <div class="mb-4">
      <%= form.submit "Search", class: "bg-orange-500 hover:bg-orange-700 text-white font-bold py-4 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
</div>

app/views/home/about.html.erb
  
<div class="container max-w-4xl mx-auto">
  <div class="contaimer bg-white rounded-3xl shadow-xl py-8 px-6">
    <h1 class="text-4xl font-bold mb-4">Rails Project Data Sources</h1>
    <p class="mb-6">The data provided is structured as a comprehensive JSON object representing a character, villages, and clans from the "Naruto" series. The structure includes several nested objects and arrays to organize various attributes and details about the character. Here is a detailed breakdown of the structures:</p>
    <section class="mb-8">
      <h2 class="text-2xl font-semibold mb-2">Characters Data Source</h2>
      <p class="mb-4"><strong>https://dattebayo-api.onrender.com/characters</strong></p>
      <table class="min-w-full bg-white border border-gray-200">
        <thead>
          <tr>
            <th class="py-2 px-4 border-b">Attribute</th>
            <th class="py-2 px-4 border-b">Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="py-2 px-4 border-b">id</td>
            <td class="py-2 px-4 border-b">A unique identifier for the character.</td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">name</td>
            <td class="py-2 px-4 border-b">The name of the character.</td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">images</td>
            <td class="py-2 px-4 border-b">An array of URLs pointing to images of the character.</td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">debut</td>
            <td class="py-2 px-4 border-b">
              An object containing details of the character's first appearance in different media:
              <ul class="list-disc pl-6">
                <li>manga: The first manga appearance.</li>
                <li>anime: The first anime appearance.</li>
                <li>novel: The first novel appearance.</li>
                <li>movie: The first movie appearance.</li>
                <li>game: The first game appearance.</li>
                <li>ova: The first OVA (original video animation) appearance.</li>
                <li>appearsIn: A list of media types the character appears in.</li>
              </ul>
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">family</td>
            <td class="py-2 px-4 border-b">
              An object detailing the character's family relationships:
              <ul class="list-disc pl-6">
                <li>father: Name of the father.</li>
                <li>mother: Name of the mother.</li>
                <li>son: Name of the son.</li>
                <li>daughter: Name of the daughter.</li>
                <li>wife: Name of the wife.</li>
                <li>adoptive son: Name of the adoptive son.</li>
                <li>godfather: Name of the godfather.</li>
              </ul>
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">jutsu</td>
            <td class="py-2 px-4 border-b">An array of jutsu (special abilities or techniques) the character can perform.</td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">natureType</td>
            <td class="py-2 px-4 border-b">An array listing the types of elemental chakra the character can use.</td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">personal</td>
            <td class="py-2 px-4 border-b">
              An object containing personal details about the character:
              <ul class="list-disc pl-6">
                <li>birthdate: The character's birth date.</li>
                <li>sex: The character's gender.</li>
                <li>age: An object detailing the character's age at different parts of the series:
                  <ul class="list-disc pl-6">
                    <li>Part I: Age during Part I.</li>
                    <li>Part II: Age during Part II.</li>
                    <li>Academy Graduate: Age at graduation from the Academy.</li>
                  </ul>
                </li>
                <li>height: An object detailing the character's height at different parts of the series.</li>
                <li>weight: An object detailing the character's weight at different parts of the series.</li>
                <li>bloodType: The character's blood type.</li>
                <li>kekkeiGenkai: An array of the character's unique bloodline abilities.</li>
                <li>classification: An array listing the character's classifications.</li>
                <li>tailedBeast: The tailed beasts associated with the character.</li>
                <li>occupation: An array of the character's occupations.</li>
                <li>affiliation: An array listing the character's affiliations.</li>
                <li>team: An array of the teams the character has been part of.</li>
                <li>clan: The name of the character's clan.</li>
                <li>titles: An array of titles and aliases associated with the character.</li>
              </ul>
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">rank</td>
            <td class="py-2 px-4 border-b">
              An object containing the character's ninja rank information:
              <ul class="list-disc pl-6">
                <li>ninjaRank: An object detailing the character's rank at different parts of the series.</li>
                <li>ninjaRegistration: The character's ninja registration number.</li>
              </ul>
            </td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">tools</td>
            <td class="py-2 px-4 border-b">An array of tools and weapons the character uses.</td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">voiceActors</td>
            <td class="py-2 px-4 border-b">
              An object containing information about the voice actors for the character:
              <ul class="list-disc pl-6">
                <li>japanese: An array of Japanese voice actors.</li>
                <li>english: An array of English voice actors.</li>
              </ul>
            </td>
          </tr>
        </tbody>
      </table>
    </section>
    <section class="mb-8">
      <h2 class="text-2xl font-semibold mb-2">Which data will be used from characters data source?</h2>
      <p class="mb-4">To create a standard profile for characters I will be using the following data from this data source:</p>
      <ul class="list-disc pl-6">
        <li>Id</li>
        <li>Name</li>
        <li>Image_1</li>
        <li>Image_2</li>
        <li>Birthdate</li>
        <li>Jutsus</li>
      </ul>
    </section>
    <section class="mb-8">
      <h2 class="text-2xl font-semibold mb-2">Clan Data Source</h2>
      <p class="mb-4"><strong>https://dattebayo-api.onrender.com/clans</strong></p>
      <table class="min-w-full bg-white border border-gray-200">
        <thead>
          <tr>
            <th class="py-2 px-4 border-b">Attribute</th>
            <th class="py-2 px-4 border-b">Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="py-2 px-4 border-b">id</td>
            <td class="py-2 px-4 border-b">A unique identifier for the clan.</td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">name</td>
            <td class="py-2 px-4 border-b">The name of the clan.</td>
          </tr>
          <tr>
            <td class="py-2 px-4 border-b">characters</td>
            <td class="py-2 px-4 border-b">An array of character IDs.</td>
          </tr>
        </tbody>
      </table>
    </section>
    <section class="mb-8">
      <h2 class="text-2xl font-semibold mb-2">Which data will be used from clans’ data source?</h2>
      <p>To link the clan from the characters table all attributes from the clan data source will be used.</p>
    </section>
  </div>
</div>

app/views/home/characters.html.erb
<div class="flex flex-wrap -mx-3 mb-5">
  <div class="w-full max-w-full px-3 mb-6 mx-auto">
    <div class="relative flex-[1_auto] flex flex-col break-words min-w-0 bg-clip-border rounded-[.95rem] border border-dashed border-stone-200 bg-white m-5">
      <!-- card body  -->
      <div class="flex-auto block py-8 px-9">
        <div>
          <div class="mb-9">
            <h1 class="mb-2 text-[1.75rem] font-semibold text-dark">All Naruto Characters</h1>
            <span class="text-[1.15rem] font-medium text-muted">Meet all Naruto characters in one place to get started.</span>
          </div>
          <div class="container mb-11">
            <%= render "home/pagination" %>
          </div>
          <div class="flex flex-wrap w-full">
            <% @characters.each do |character| %>
              <div class="flex flex-col mr-5 text-center mb-11 lg:mr-16">
                <div class="inline-block mb-4 relative shrink-0 rounded-[.95rem]">
                  <img class="inline-block shrink-0 rounded-[.95rem] w-[150px] h-[150px]" src="<%= character.image_1 %>" alt="<%= character.name %> image">
                </div>
                <div class="text-center">
                  <a href="javascript:void(0)" class="text-dark font-semibold hover:text-primary text-[1.25rem] transition-colors duration-200 ease-in-out"><%= character.name %></a>
                  <%# Button %>
                  <div class="container">
                    <%= link_to "More...", home_character_path(character), class: 'relative inline-flex text-sm sm:text-base rounded-full font-medium border-2 border-transparent transition-colors outline-transparent focus:outline-transparent disabled:opacity-50 disabled:pointer-events-none disabled:opacity-40 disabled:hover:opacity-40 disabled:cursor-not-allowed disabled:shadow-none text-white bg-[#4040F2] hover:bg-[#3333D1] focus:border-[#B3B3FD] focus:bg-[#4040F2] px-4 py-1 sm:py-1.5 sm:px-5' %>
                  </div>
                  <%# End button %>
                </div>
              </div>
            <% end %>
          </div>
          <%= render "home/pagination" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/clan_characters.html.erb
<div class="flex flex-wrap -mx-3 mb-5">
  <div class="w-full max-w-full px-3 mb-6 mx-auto">
    <div class="relative flex-[1_auto] flex flex-col break-words min-w-0 bg-clip-border rounded-[.95rem] border border-dashed border-stone-200 bg-white m-5">
      <!-- card body  -->
      <div class="flex-auto block py-8 px-9">
        <div>
          <div class="mb-9">
            <h1 class="mb-2 text-[1.75rem] font-semibold text-dark"><%= @clan.name %> Characters</h1>
            <span class="text-[1.15rem] font-medium text-muted">Meet all characters from the <%= @clan.name %> clan.</span>
          </div>
          <div class="container mb-11">
            <%= render "home/pagination" %>
          </div>
          <div class="flex flex-wrap w-full">
            <% if @characters.any? %>
              <% @characters.each do |character| %>
                <div class="flex flex-col mr-5 text-center mb-11 lg:mr-16">
                  <div class="inline-block mb-4 relative shrink-0 rounded-[.95rem]">
                    <img class="inline-block shrink-0 rounded-[.95rem] w-[150px] h-[150px]" src="<%= character.image_1 %>" alt="<%= character.name %> image">
                  </div>
                  <div class="text-center">
                    <a href="javascript:void(0)" class="text-dark font-semibold hover:text-primary text-[1.25rem] transition-colors duration-200 ease-in-out"><%= character.name %></a>
                    <%# Button %>
                    <div class="container">
                      <%= link_to "More...", home_character_path(character), class: 'relative inline-flex text-sm sm:text-base rounded-full font-medium border-2 border-transparent transition-colors outline-transparent focus:outline-transparent disabled:opacity-50 disabled:pointer-events-none disabled:opacity-40 disabled:hover:opacity-40 disabled:cursor-not-allowed disabled:shadow-none text-white bg-[#4040F2] hover:bg-[#3333D1] focus:border-[#B3B3FD] focus:bg-[#4040F2] px-4 py-1 sm:py-1.5 sm:px-5' %>
                    </div>
                    <%# End button %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div class="w-full text-center">
                <p class="text-lg font-medium text-muted">No characters found for the selected clan.</p>
              </div>
            <% end %>
          </div>
          <%= render "home/pagination" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/clans.html.erb
<div class="flex flex-wrap -mx-3 mb-5">
  <div class="w-full max-w-full px-3 mb-6 mx-auto">
    <div class="relative flex-[1_auto] flex flex-col break-words min-w-0 bg-clip-border rounded-[.95rem] border border-dashed border-stone-200 bg-white m-5">
      <!-- card body  -->
      <div class="flex-auto block py-8 px-9">
        <div>
          <div class="mb-9">
            <h1 class="mb-2 text-[1.75rem] font-semibold text-dark">All Clans</h1>
            <span class="text-[1.15rem] font-medium text-muted">Meet all clans in one place to get started.</span>
          </div>
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Clan Name
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <% @clans.each do |clan| %>
                <tr>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <h2 class="text-dark font-semibold hover:text-primary text-[1.25rem] transition-colors duration-200 ease-in-out"><%= clan.name %></h2>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <%= link_to "Show Characters", clan_characters_path(clan), class: 'relative inline-flex text-sm sm:text-base rounded-full font-medium border-2 border-transparent transition-colors outline-transparent focus:outline-transparent disabled:opacity-50 disabled:pointer-events-none disabled:opacity-40 disabled:hover:opacity-40 disabled:cursor-not-allowed disabled:shadow-none text-white bg-[#4040F2] hover:bg-[#3333D1] focus:border-[#B3B3FD] focus:bg-[#4040F2] px-4 py-1 sm:py-1.5 sm:px-5' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container flex justify-center items-center">
  <%= render "home/searchForm" %>
</div>

<div class="container flex justify-center items-center">
  <p class="text-lg text-white">Naruto, Sasuke, Madara, Kakashi, and more...</p>
</div>

app/views/home/search.html.erb
<%= render "home/searchForm" %>

<div class="flex flex-wrap -mx-3 mb-5">
  <div class="w-full max-w-full px-3 mb-6 mx-auto">
    <div class="relative flex-[1_auto] flex flex-col break-words min-w-0 bg-clip-border rounded-[.95rem] border border-dashed border-stone-200 bg-white m-5">
      <!-- card body  -->
      <div class="flex-auto block py-8 px-9">
        <div>
          <div class="mb-9">
            <h1 class="mb-2 text-[1.75rem] font-semibold text-dark">Search Results</h1>
            <span class="text-[1.15rem] font-medium text-muted">Showing search results for your query.</span>
          </div>
          <div class="container mb-11">
            <%= render "home/pagination" %>
          </div>
          <div class="flex flex-wrap w-full">
            <% if @characters.any? %>
              <% @characters.each do |character| %>
                <div class="flex flex-col mr-5 text-center mb-11 lg:mr-16">
                  <div class="inline-block mb-4 relative shrink-0 rounded-[.95rem]">
                    <img class="inline-block shrink-0 rounded-[.95rem] w-[150px] h-[150px]" src="<%= character.image_1 %>" alt="<%= character.name %> image">
                  </div>
                  <div class="text-center">
                    <a href="javascript:void(0)" class="text-dark font-semibold hover:text-primary text-[1.25rem] transition-colors duration-200 ease-in-out"><%= character.name %></a>
                    <%# Button %>
                    <div class="container">
                      <%= link_to "More...", home_character_path(character), class: 'relative inline-flex text-sm sm:text-base rounded-full font-medium border-2 border-transparent transition-colors outline-transparent focus:outline-transparent disabled:opacity-50 disabled:pointer-events-none disabled:opacity-40 disabled:hover:opacity-40 disabled:cursor-not-allowed disabled:shadow-none text-white bg-[#4040F2] hover:bg-[#3333D1] focus:border-[#B3B3FD] focus:bg-[#4040F2] px-4 py-1 sm:py-1.5 sm:px-5' %>
                    </div>
                    <%# End button %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div class="w-full text-center">
                <p class="text-lg font-medium text-muted">No characters found for the selected clan.</p>
              </div>
            <% end %>
          </div>
          <%= render "home/pagination" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RailsProjectDlopez</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.png') %>
          <!-- stylesheet -->

  </head>

  <body>
    <%= render "home/header" %>
    <%= yield %>
    <%= render "home/footer" %>
  </body>
</html>